"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os

import warnings

import dj_database_url

from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent

if os.path.isfile("env.py"):

    import env

DEBUG = os.environ.get("DEVELOPMENT", "False") == "True"

_secret_key = os.environ.get("SECRET_KEY", "")

if not _secret_key:

    if not DEBUG:

        raise ImproperlyConfigured(

            "The SECRET_KEY environment variable must be set in production."

        )

    warnings.warn(

        "SECRET_KEY is not set; using an insecure dev-only default. "

        "Do not use this in production.",

        stacklevel=2,

    )

    _secret_key = "django-insecure-dev-key-only-for-local-development"

SECRET_KEY = _secret_key

ALLOWED_HOSTS = [".herokuapp.com", "localhost", "127.0.0.1"]

INSTALLED_APPS = [

    'daphne',

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'django.contrib.sites',

    'channels',

    'allauth',

    'allauth.account',

    'allauth.socialaccount',

    'cloudinary',

    'cloudinary_storage',

    'axes',

    'motormatch',

    'apps.users',

    'apps.vehicles',

    'apps.messaging',

    'apps.notifications',

]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'csp.middleware.CSPMiddleware',

    'apps.users.middleware.IpRateLimitMiddleware',

    'axes.middleware.AxesMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',

    'apps.users.middleware.OnlinePresenceMiddleware',

    'apps.users.middleware.BanSuspendMiddleware',

]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [

            BASE_DIR / 'templates',

            BASE_DIR / 'motormatch' / 'templates',

        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]

WSGI_APPLICATION = 'config.wsgi.application'

if os.environ.get("DATABASE_URL"):

    DATABASES = {

        "default": dj_database_url.parse(

            os.environ.get("DATABASE_URL"),

            conn_max_age=600,

            ssl_require=True,

        )

    }

else:

    DATABASES = {

        'default': {

            'ENGINE': 'django.db.backends.sqlite3',

            'NAME': BASE_DIR / 'db.sqlite3',

        }

    }

AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' if not DEBUG else 'django.contrib.staticfiles.storage.StaticFilesStorage'

STATICFILES_DIRS = [

    BASE_DIR / 'static',

]

REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')

_redis_ssl_opts = {'ssl_cert_reqs': None} if REDIS_URL.startswith('rediss://') else {}

CACHES = {

    'default': {

        'BACKEND': 'django_redis.cache.RedisCache',

        'LOCATION': REDIS_URL,

        'OPTIONS': {

            'CLIENT_CLASS': 'django_redis.client.DefaultClient',

            'IGNORE_EXCEPTIONS': True,

            'CONNECTION_POOL_KWARGS': _redis_ssl_opts,

        },

        'TIMEOUT': 300,

    }

}

ASGI_APPLICATION = 'config.asgi.application'

_channel_redis_url = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/2')
_channel_host = {'address': _channel_redis_url, **({'ssl_cert_reqs': None} if _channel_redis_url.startswith('rediss://') else {})}

CHANNEL_LAYERS = {

    'default': {

        'BACKEND': 'channels_redis.core.RedisChannelLayer',

        'CONFIG': {

            'hosts': [_channel_host],

        },

    },

}

CLOUDINARY_STORAGE = {

    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),

    'API_KEY':    os.environ.get('CLOUDINARY_API_KEY', ''),

    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),

}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [

    'axes.backends.AxesStandaloneBackend',

    'django.contrib.auth.backends.ModelBackend',

    'allauth.account.auth_backends.AuthenticationBackend',

]

AXES_FAILURE_LIMIT       = 5

AXES_COOLOFF_TIME        = 1

AXES_LOCKOUT_PARAMETERS  = ['username', 'ip_address']

AXES_RESET_ON_SUCCESS    = True

AXES_ENABLE_ADMIN        = True

AXES_VERBOSE             = False

SITE_ID = 1

ACCOUNT_EMAIL_VERIFICATION = 'none'

ACCOUNT_AUTHENTICATION_METHOD = 'email'

ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_USERNAME_REQUIRED = False

ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True

ACCOUNT_LOGIN_ON_SIGNUP = True

ACCOUNT_FORMS = {'signup': 'apps.users.forms.CustomSignupForm'}

ACCOUNT_ADAPTER = 'motormatch.adapters.AccountAdapter'

ACCOUNT_SESSION_REMEMBER = None

SESSION_COOKIE_AGE = 30 * 24 * 60 * 60

LOGIN_URL = '/accounts/login/'

LOGIN_REDIRECT_URL = '/'

ACCOUNT_LOGOUT_REDIRECT_URL = '/'

CSRF_TRUSTED_ORIGINS = [

    "https://*.codeinstitute-ide.net",

    "https://*.herokuapp.com",

]

if not DEBUG:

    SECURE_PROXY_SSL_HEADER        = ('HTTP_X_FORWARDED_PROTO', 'https')

    SECURE_SSL_REDIRECT            = True

    SECURE_HSTS_SECONDS            = 31536000

    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD            = True

    SECURE_CONTENT_TYPE_NOSNIFF    = True

    SECURE_REFERRER_POLICY         = 'strict-origin-when-cross-origin'

    SESSION_COOKIE_SECURE          = True

    CSRF_COOKIE_SECURE             = True

    X_FRAME_OPTIONS                = 'DENY'

TENOR_API_KEY = os.environ.get('TENOR_API_KEY', '')

DVLA_API_KEY  = os.environ.get('DVLA_API_KEY', '')

CSP_DEFAULT_SRC    = ("'self'",)
CSP_SCRIPT_SRC     = ("'self'", 'cdn.jsdelivr.net')
CSP_STYLE_SRC      = ("'self'", "'unsafe-inline'", 'cdn.jsdelivr.net', 'fonts.googleapis.com')
CSP_FONT_SRC       = ("'self'", 'cdn.jsdelivr.net', 'fonts.gstatic.com')
CSP_IMG_SRC        = ("'self'", 'data:', 'res.cloudinary.com', '*.tenor.com', 'images.unsplash.com', 'i.pravatar.cc', 'flagcdn.com')
CSP_CONNECT_SRC    = ("'self'",)
CSP_OBJECT_SRC     = ("'none'",)
CSP_BASE_URI       = ("'self'",)
CSP_FRAME_ANCESTORS = ("'none'",)
CSP_FORM_ACTION    = ("'self'",)
CSP_INCLUDE_NONCE_IN = ['script-src']
