from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('vehicle/<int:pk>/', views.vehicle_detail, name='vehicle_detail'),
    path('vehicle/<int:pk>/save/', views.save_vehicle, name='save_vehicle'),
    path('vehicle/<int:pk>/bid/', views.place_bid, name='place_bid'),
    path('vehicle/<int:pk>/review/', views.add_review, name='add_review'),
    path('vehicle/<int:pk>/message/', views.send_message, name='send_message'),
    path('vehicle/<int:pk>/delete/', views.delete_vehicle, name='delete_vehicle'),
    path('vehicle/<int:pk>/edit/', views.edit_vehicle, name='edit_vehicle'),
    path('seller/<int:pk>/', views.seller_profile, name='seller_profile'),
    path('compare/', views.comparison, name='comparison'),
    path('saved/', views.saved, name='saved'),
    path('sell/', views.sell, name='sell'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('offers/', views.offers, name='offers'),
    path('offer-submitted/', views.offer_submitted, name='offer_submitted'),
    path('enquiry-sent/', views.enquiry_sent, name='enquiry_sent'),
    path('notifications/', views.notifications_list, name='notifications'),
    path('notifications/<int:pk>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/poll/', views.notifications_poll, name='notifications_poll'),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/<int:user_pk>/', views.conversation, name='conversation'),
    path('inbox/<int:user_pk>/send/', views.send_message_ajax, name='send_message_ajax'),
    path('inbox/<int:user_pk>/poll/', views.poll_messages, name='poll_messages'),
    path('inbox/<int:user_pk>/typing/', views.set_typing, name='set_typing'),
    path('inbox/<int:user_pk>/delete/', views.delete_conversation, name='delete_conversation'),
    path('messages/send/', views.send_message, name='send_message_direct'),
    path('bids/<int:pk>/respond/', views.respond_bid, name='respond_bid'),
    path('bids/<int:pk>/bidder-respond/', views.bidder_respond_bid, name='bidder_respond_bid'),
    path('security/login/<int:pk>/', views.login_event_detail, name='login_event_detail'),
    path('security/login/<int:pk>/confirm/', views.confirm_login_event, name='confirm_login_event'),
    path('api/dvla/', views.dvla_lookup, name='dvla_lookup'),
]
