# Generated by Django 4.2.27 on 2026-03-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('variant', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('fuel', models.CharField(max_length=50)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('badge_color', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
