# Generated by Django 4.2.27 on 2026-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motormatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
