# Generated by Django 4.2.28 on 2026-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motormatch', '0006_login_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='counter_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
