# Generated by Django 4.2.28 on 2026-03-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motormatch', '0008_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
