# Generated by Django 4.2.28 on 2026-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motormatch', '0009_vehicle_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badge',
            field=models.CharField(blank=True, choices=[('', 'None'), ('member', 'Member'), ('verified', 'Verified'), ('trusted', 'Trusted'), ('top_seller', 'Top Seller'), ('dealer', 'Dealer'), ('staff', 'Staff')], default='', max_length=20),
        ),
    ]
