# Generated by Django 4.2.28 on 2026-03-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motormatch', '0010_userprofile_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='gif_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
