# Generated by Django 4.2.28 on 2026-03-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motormatch', '0012_alter_message_attachment_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
