# Generated by Django 4.2.28 on 2026-03-06 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motormatch', '0014_add_approval_suspension_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='BannedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=200, unique=True)),
                ('severity', models.CharField(choices=[('flag', 'Flag for review'), ('delete', 'Auto-delete (hate speech / slurs)')], default='flag', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('hate', 'Hate Speech'), ('fraud', 'Fraud / Scam'), ('spam', 'Spam'), ('violence', 'Violence'), ('adult', 'Adult Content'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_keywords_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
