# Generated by Django 4.2.28 on 2026-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motormatch', '0018_add_vehicle_message_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='listing_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_sale', 'Pending Sale'), ('sold', 'Sold'), ('removed', 'Removed')], db_index=True, default='active', max_length=20),
        ),
    ]
