# Generated by Django 4.2.28 on 2026-03-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motormatch', '0020_add_vehicle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedMessage',
            fields=[
            ],
            options={
                'verbose_name': 'Flagged message',
                'verbose_name_plural': 'Flagged messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('motormatch.message',),
        ),
    ]
